### PR TITLE
Make the task failed when SpotBugs found violation

### LINKED ISSUE #51: Build should fail when bugs detected
Seems like behavior of spotbugs/spotbugs#873 was accidentally enabled :)

I will add a test which I expect to fail when a warning is found.

### PR DESCRIPTION
**Pull request by KengoTODA**
@DPUkyle I made this PR to add fixes for #51. Please have a review.

Close #51
Close #52

### CODE REVIEW

File: src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java [hunk 1]
```diff
@@ -80,7 +83,16 @@ public void execute() {
 
       try {
         edu.umd.cs.findbugs.Version.printVersion(false);
-        edu.umd.cs.findbugs.FindBugs2.main(args);
+        try (FindBugs2 findBugs2 = new FindBugs2()) {
```
Comment (DPUkyle) [inline src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java:86]: Looks great. I'm hoping that this style of initializing a new `FindBugs2` instance for each worker execution should work well.

**Review by DPUkyle — APPROVED** [review]
Looks great!

File: src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java (hunk 1 above)
Comment (KengoTODA) [reply src/main/groovy/com/github/spotbugs/snom/internal/SpotBugsRunnerForWorker.java:86]: hope that it works with the support from isolated process and classloader :)
